spring:
  datasource:
    username: root
    password:
    url: jdbc:mysql://localhost:3306/persion?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
    driver-class-name: com.mysql.cj.jdbc.Driver